# Some Basic PyTorch functions

An short introduction about PyTorch and about the chosen functions. 

- as_tensor
- zeros & ones
- linspace
- cat
- t

Before we begin, let's install and import PyTorch

In [3]:
# Import torch and other required modules
import torch

## Function 1 - as_tensor

This function converts any array like data-structure to tensor.Tensor. If the data is already a Tensor with the same dtype and device, no copy will be performed, otherwise a new Tensor will be returned with computational graph retained if data Tensor has requires_grad=True

In [ ]:
# Example 1 - working (change this)
import numpy
a = numpy.array([1, 2, 3])
t = torch.as_tensor(a)
t

tensor([1, 2, 3])

First imported numpy and created a numpy array then passing the numpy array into the as_tensor function to convert the numpy array to a tensor

In [ ]:
# Example 2 - working
l = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
t = torch.as_tensor(l)
t

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

Here we have declared a 2-D list and passed into as_tensor function.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
d = {1:[4, 5, 6], 2:[7, 8, 9, 8]}
t = torch.as_tensor(d)

RuntimeError: ignored

The as_tensor only supports array like data structures, so didn't worked with dictionary

Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [25]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anurag3301/01-tensor-operations


'https://jovian.ai/anurag3301/01-tensor-operations'

## Function 2 - zeros & ones

Creates return a tensor filled with sclar value 0 with function zeros method and 1 with ones method.

In [ ]:
# Example 1 - working
t = torch.zeros(2, 3)
t

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Here we pass no of rows and columns in the zeros method to create a tensor with sclar value 0

In [ ]:
# Example 2 - working
t = torch.ones(2, 3)
t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Here we pass no of rows and columns in the ones method to create a tensor with sclar value 1

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
t = torch.ones("s")
t

TypeError: ignored

Always enter an integer as argumnet of dimessions

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anurag3301/01-tensor-operations


'https://jovian.ai/anurag3301/01-tensor-operations'

## Function 3 - Linspace
Creates a one-dimensional tensor of size `steps` whose values are evenly spaced from `start` to `end`


In [ ]:
# Example 1 - working
t = torch.linspace(3, 10, steps=5)
t

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

We want 5 numbers B/W 3 and 10 which are evenly distributed.

In [ ]:
# Example 2 - working
t = torch.linspace(start=-10, end=10, steps=5)
t

tensor([-10.,  -5.,   0.,   5.,  10.])

We have given -10 for start and 10 to end and 5 to step so we want 5 numbers B/W -10 and 10.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
t = torch.linspace(10, 3, steps=5.)
t

TypeError: ignored

Steps cannot have any value other than an integer

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 4 - cat

This function is used to concatenates tensors in given dimension.

In [4]:
l = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
t = torch.as_tensor(l)
t

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [6]:
# Example 1 - working
torch.cat((t, t), 0)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

First we have created an 2D tensor t and then passed it into cat function 2 time and set the dimenssion as 0

In [7]:
# Example 2 - working
torch.cat((t, t, t), 1)

tensor([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10]])

Here we have passed the tensor t 3 times in the cat function and set the dimenssion as 1

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
torch.cat((t, t), 2)

IndexError: ignored

The dimenssion can either be 0 or 1

Closing comments about when to use this function

In [11]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anurag3301/01-tensor-operations


'https://jovian.ai/anurag3301/01-tensor-operations'

## Function 5 - t

The function t transposes the 0 and 1 dimessions. The tensor A[ i x j ] becomes A[ j x i ]

In [13]:
t

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [12]:
# Example 1 - working
torch.t(t)

tensor([[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]])

Here we have used the t tensor from the previous cell and passed in the function `t` so that the dimenssions get transposed. So the [2x5] get converted to [5x2]

In [14]:
d = torch.cat((t, t), 0)
d

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [15]:
# Example 2 - working
torch.t(d)

tensor([[ 1,  6,  1,  6],
        [ 2,  7,  2,  7],
        [ 3,  8,  3,  8],
        [ 4,  9,  4,  9],
        [ 5, 10,  5, 10]])

First we have taken a tensor d then passed into the t function so the dimension [4x5] becomes [5x4]

In [21]:
# Example 3 - breaking (to illustrate when it breaks)

# Well I never brakes if you pass a tensor

tensor([])

Explanation about example

Closing comments about when to use this function

In [22]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anurag3301/01-tensor-operations


'https://jovian.ai/anurag3301/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


In [26]:
jovian.submit(assignment="zerotogans-a1")

[jovian] Detected Colab notebook...


[jovian] Error: Please provide the project argument e.g. jovian.commit(project='my-project')
