> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# My Favorite Five NumPy Function

 
### Here I have given some of my favourite NumPy function which are very useful according to me

NumPy is a Python Library which let us do lot of advanced methanetical operation over multi-dimensional arrays and matrices in a very fast and resource conservative manner.

- array
- concatenate
- repeat
- random
- sort

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [6]:
# List of functions explained 
function1 = np.array  # (change this)
function2 = np.concatenate
function3 = np.repeat
function4 = np.random
function5 = np.sort

## Function 1 - np.array

The `array` function is used to create a numpy array from a python list

In [7]:
list_1 = [2, 4, 6, 8]
print(list_1, type(list_1))

arr_1 = np.array(list_1)
print(arr_1, type(arr_1))

[2, 4, 6, 8] <class 'list'>
[2 4 6 8] <class 'numpy.ndarray'>


Here we have declared a python list named "list_1" on line 1 and printed the list and type on the 2nd line.
Then we have passed "list_1" in the array function of NumPy to create the NumPy array of the list and stored it in a variable named "arr_1" and printed the array and its type in line 5.

In [8]:
# Example 2 - working
arr_2 = np.array((11122.55666, 4514.668, 7845), dtype = np.float64)
print(arr_2, type(arr_2))
print(arr_2[1])

[11122.55666  4514.668    7845.     ] <class 'numpy.ndarray'>
4514.668


Again here have created NumPy Array here and here we have also explicitly defined the Numpy dtype or Data Type as float64

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
arr_3 = np.array({1, 1.6, 23})
print(arr_3[1])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

You should not make NumPy array out of iterable other than Python list 

Some closing comments about when to use this function.

In [10]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "anurag3301/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/anurag3301/numpy-array-operations


'https://jovian.ml/anurag3301/numpy-array-operations'

## Function 2 - concatenate

This function is use to concatenate or join two or more numpy array.

In [11]:
# Example 1 - working

x = np.array((1, 2, 3))
y = np.array((4, 5, 6))
z = np.array((7, 8, 9))

arr_concatinated = np.concatenate((x, y, z))

print(arr_concatinated)

[1 2 3 4 5 6 7 8 9]


Here we have declared 3 numpy array as "x", "y", "z". and passed them into concatenate function and stored the finaly result in arr_concatinated and printed it.

In [12]:
# Example 2 - working
a = np.array([[10.5, 2], [3, 4]])
b = np.array([[5, 6.7], [8, 9.6]])

con_x_axis = np.concatenate((a, b), axis=0)
con_y_axis = np.concatenate((a, b), axis=1)

print(con_x_axis)
print()
print(con_y_axis)

[[10.5  2. ]
 [ 3.   4. ]
 [ 5.   6.7]
 [ 8.   9.6]]

[[10.5  2.   5.   6.7]
 [ 3.   4.   8.   9.6]]


In this example we gave one more argument known as "axis". It let us define the way or direction we want to concatinate the multi-dimenssional arrays. In our case we have two 2D arrays and we concatinated them in two axis ie. X-axis in and then Y-axis.

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
m = [[1, 2], [1, 5, 7]]
n = [[1, 9]]

m_n = np.concatenate((m, n))

print(m_n)

<__array_function__ internals>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

Before concatinating arrays, Check the dimenssion that they can be concatinated or not.

This is one of this most important function as you may encounter a lot of situation where where you have to join different arryas.

In [ ]:
jovian.commit()

## Function 3 - repeat

This function is used to create an array of a single repeating item.

In [ ]:
# Example 1 - working
arr_4 = np.repeat(5.4, 8)

print(arr_4)

Here we used repeate function to and passed two argument. First one the item you want to repeate and the second one how many time you want to repeate the item. Here we repeated 5.4, 8 times 

In [14]:
# Example 2 - working
arr_5 = np.array((1, 3, 4))
arr_6 = np.repeat(arr_5, 5)
print(arr_6)

[1 1 1 1 1 3 3 3 3 3 4 4 4 4 4]


Here we have passed an existing array as an argument and repeated the elements of that array n times.

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
arr_4 = np.repeat([1, 2, 3], [4, 5])

print(arr_4)

ValueError: operands could not be broadcast together with shape (3,) (2,)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [16]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "anurag3301/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/anurag3301/numpy-array-operations


'https://jovian.ml/anurag3301/numpy-array-operations'

## Function 4 - random

Here actually random is not a funciton it is a class inside NumPy, which holds lot of function to generate random element array.

In [17]:
# Example 1 - working
rand_arr1 = np.random.randint(low = 10, high = 50, size = 10)

print(rand_arr1)

[32 10 42 43 27 41 18 21 43 13]


Here we have used randint function of random class to generate an array of randon intigers. Here the low argument is the lowest number in range and the high argument is the highest number in range and the size argument tell how many random element is to be stored in the array. 

In [18]:
# Example 2 - working
rand_arr2 = np.random.uniform(low = 10, high = 50, size = (5, 4))

print(rand_arr2)

[[23.03922816 32.18162687 15.65870201 14.29108655]
 [14.0845365  31.96840131 16.31985774 45.0101382 ]
 [28.7613649  10.09763569 47.11233332 41.12170443]
 [40.12736964 35.02942273 12.23517772 32.50352266]
 [27.44632859 16.92969386 20.07206545 40.03542408]]


Here we used the uniform function to create random float and we can pass a tuple of numbers to the size argument to create random multi-dimenssional array

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
rand_arr3 = np.random.randint(low = 60, high = 20, size = 10)

print(rand_arr3)

ValueError: low >= high

Do not use a greater number for low argument than the high argument.

It is a very useful class to use when you are creating a game where you want random actions.

In [ ]:
jovian.commit()

## Function 5 - sort

This function is used to sort a numpy array in may different way and orders.

In [20]:
# Example 1 - working
unsorted_array = np.array([3, 8, 5, 45, 65, 74])

sorted_array = np.sort(unsorted_array)

print(sorted_array)

[ 3  5  8 45 65 74]


Here we first define a unsorted array with some random numbers. Then pass the unsored array in the NumPy sort function and store the resut in a variable and then print the sorted array.

In [30]:
# Example 2 - working
unsorted_array2 = np.array([[3, 8, 5], [45, 65, 74], [8, 64, 7]])

sorted_array2 = np.sort(unsorted_array2, axis=0, kind='heapsort')

print(sorted_array2)

[[ 3  8  5]
 [ 8 64  7]
 [45 65 74]]


Here we have provided some extra argument in the sort function first is axis, The direction you want to sort. The the "kind" argumnet which have some values like 'quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’. The all have different way of sorting algorithms resulting to different Time Complexity.

In [32]:
# Example 3 - breaking (to illustrate when it breaks)
sorted_array2 = np.sort(unsorted_array2, axis=2, kind='heapsort')

print(sorted_array2)

AxisError: axis 2 is out of bounds for array of dimension 2

Do not give wrong Axis number.

It is a very useful function, and save you a lot of time while sorting large data sets. 

In [33]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "anurag3301/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/anurag3301/numpy-array-operations


'https://jovian.ml/anurag3301/numpy-array-operations'

## Conclusion

So in this the notebook Where I given a little discription of some of the basic function which are very useful while working with large dataset.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
